vscode:
  extensions:
    - PKief.material-icon-theme
    - ms-playwright.playwright

image:
  file: .gitpod.Dockerfile

tasks:
  - name: 'Setup'
    command: |
      curl -fsSL https://bun.sh/install | bash
      source /home/gitpod/.bashrc
      npm install -g npm@9.1.3
      npm install

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
  - port: 10000
    onOpen: ignore
